import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#faf9f6",
        surface: "#faf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "surface-container": "#efeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "on-surface": "#1a1c1a",
        "on-surface-variant": "#4d4635",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f2f1ee",
        outline: "#7f7663",
        "outline-variant": "#d0c5af",
        "surface-tint": "#735c00",
        primary: "#735c00",
        "on-primary": "#ffffff",
        "primary-container": "#d4af37",
        "on-primary-container": "#554300",
        "inverse-primary": "#e9c349",
        secondary: "#7a5642",
        "on-secondary": "#ffffff",
        "secondary-container": "#fecdb4",
        "on-secondary-container": "#795541",
        tertiary: "#486730",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9abd7d",
        "on-tertiary-container": "#2f4c19",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c349",
        "on-primary-fixed": "#241a00",
        "on-primary-fixed-variant": "#574500",
        "secondary-fixed": "#ffdbca",
        "secondary-fixed-dim": "#ecbda4",
        "on-secondary-fixed": "#2e1506",
        "on-secondary-fixed-variant": "#603f2d",
        "tertiary-fixed": "#c9eea9",
        "tertiary-fixed-dim": "#aed18f",
        "on-tertiary-fixed": "#0b2000",
        "on-tertiary-fixed-variant": "#314e1b",
        "surface-variant": "#e3e2e0",
      },
      fontFamily: {
        display: ["var(--font-playfair)", "Georgia", "serif"],
        body: ["var(--font-montserrat)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "80px",
        "container-padding": "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        gutter: "24px",
      },
      boxShadow: {
        ambient: "0 8px 32px rgba(220, 174, 150, 0.1)",
      },
    },
  },
  plugins: [],
};
export default config;
